default: &default
  adapter: postgresql
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'postgres' } %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anisync_development

test:
  <<: *default
  database: anisync_test

production:
  url: <%= ENV['DATABASE_URL'] %>
