name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  RAILS_ENV: test
  NODE_ENV: test

jobs:
  lint:
    name: Lint and Security
    runs-on: ubuntu-latest
    container: ruby:3.0.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs $(nproc) --retry 3

      - name: Run security checks
        run: |
          bin/bundler-audit --update
          bin/brakeman -q -w2

      - name: Run linters
        run: |
          bin/rubocop --parallel
  test:
    name: Tests
    runs-on: ubuntu-latest
    container: ruby:3.0.3
    env:
      ImageOS: ubuntu20
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: anisync_test
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Ruby Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs $(nproc) --retry 3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:seed

      - name: Run unit tests
        run: |
          bin/rails test
